title: my color blog
author: Lagarden
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 A blog of color

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
